### ISSUE TITLE
Add PR/issue management things

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/software-templates#3]
Require PR labels:

```yaml
on:
  pull_request:
    types:
      - opened
      - labeled

jobs:
  check_priority_label:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for required priority labels"
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'priority:low') && 
                !contains(github.event.pull_request.labels.*.name, 'priority:medium') && 
                !contains(github.event.pull_request.labels.*.name, 'priority:high')}}
        run: exit 1
```
